# Config
SIZES = {
    'basic': 299
}

NUM_CHANNELS = 3
NUM_CLASSES = 5
GENERATOR_BATCH_SIZE = 32
TOTAL_EPOCHS = 100
STEPS_PER_EPOCH = 500
VALIDATION_STEPS = 50
BASE_DIR = 'D:\\nswf_model_training_data\\data'